export const LOGOUT = 'LOGOUT';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const ADD_INVOICE = 'ADD_INVOICE';
export const REQUEST_INVOICES = 'REQUEST_INVOICES';
export const REQUEST_INVOICES_ERROR = 'REQUEST_INVOICES_ERROR';
export const REQUEST_PAYMENTS = 'REQUEST_PAYMENTS';
export const REQUESTING_PAYMENTS = 'REQUESTING_PAYMENTS';
export const REQUEST_PAYMENTS_ERROR = 'REQUEST_PAYMENTS_ERROR';
export const REQUESTING_INVOICES = 'REQUESTING_INVOICES';
export const REQUEST_ADD_INVOICE = 'REQUEST_ADD_INVOICE'
export const REQUESTING_ADD_INVOICE = 'REQUESTING_ADD_INVOICE'
export const REQUEST_ADD_INVOICES_ERROR = 'REQUEST_ADD_INVOICES_ERROR'

export const GET = 'GET';
export const POST = 'POST';

export const BASE_URI = '';
export const REQUEST_INVOICES_URI = BASE_URI+'REQUEST_INVOICES_URI';
export const REQUEST_PAYMENTS_URI = BASE_URI+'REQUEST_PAYMENTS_URI';
export const REQUEST_ADD_INVOICES_URI = BASE_URI+'REQUEST_ADD_INVOICES_URI';
